name: enum_string_value_generator
description: It's append String expressions/values for your own enum classes!
version: 2.0.0
homepage: https://github.com/kikuchy/enum_string_value

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  analyzer: ^1.3.0
  source_gen: ^1.0.0
  code_builder: ^3.7.0
  enum_string_value_lib: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
