name: enum_string_value_generator
description: It's append String expressions/values for your own enum classes!
version: 0.0.2+3
homepage: https://github.com/kikuchy/enum_string_value

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  build: ^1.6.2
  analyzer: ^0.41.2
  source_gen: ^0.9.10+3
  code_builder: ^3.6.0
  enum_string_value_lib: ^1.0.0+2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.14.2
